import Foundation

struct CloudError: Error, CustomStringConvertible {
    let description: String
    init(_ description: String) { self.description = description }
}
struct CommandFailure: Error { let status: Int32 }
struct Product: Decodable { let bundleIdentifier: String; let marketingVersion: String }
struct CloudIdentity {
    let bundleID: String
    let team: String
    let build: String
    var configuration: String {
        "// Generated by Xcode Cloud; never commit.\nDEVELOPMENT_TEAM = \(team)\nCURRENT_PROJECT_VERSION = \(build)\n"
    }
}
func requireCloud(_ condition: Bool, _ message: String) throws {
    guard condition else { throw CloudError(message) }
}
func matches(_ value: String, _ expression: String) -> Bool {
    value.range(of: expression, options: .regularExpression)?.lowerBound == value.startIndex
        && value.range(of: expression, options: .regularExpression)?.upperBound == value.endIndex
}
func identity(_ environment: [String: String], product: Product) throws -> CloudIdentity {
    let bundle = environment["CI_BUNDLE_ID"] ?? ""
    let team = environment["CI_TEAM_ID"] ?? ""
    let build = environment["CI_BUILD_NUMBER"] ?? ""
    try requireCloud(environment["CI"] == "TRUE", "This adapter requires Xcode Cloud (CI=TRUE).")
    try requireCloud(matches(product.bundleIdentifier, #"[A-Za-z0-9-]+(?:\.[A-Za-z0-9-]+)+"#)
        && !product.bundleIdentifier.lowercased().hasPrefix("com.example."), "Product identity must be concrete.")
    try requireCloud(bundle == product.bundleIdentifier, "CI_BUNDLE_ID must match Config/Product.json.")
    try requireCloud(matches(team, #"[A-Z0-9]{10}"#) && team != "XXXXXXXXXX" && team != "YOURTEAMID", "CI_TEAM_ID must be a concrete 10-character Apple team ID.")
    try requireCloud(matches(build, #"[1-9][0-9]{0,17}"#), "CI_BUILD_NUMBER must be a positive decimal integer.")
    return CloudIdentity(bundleID: bundle, team: team, build: build)
}
func nativeAction(_ environment: [String: String]) throws -> (String, Int32) {
    guard let action = environment["CI_XCODEBUILD_ACTION"],
          ["analyze", "archive", "build", "build-for-testing", "test-without-building"].contains(action),
          let raw = environment["CI_XCODEBUILD_EXIT_CODE"],
          let status = Int32(raw), (0...255).contains(status) else {
        throw CloudError("Missing or invalid Xcode Cloud action/exit status.")
    }
    return (action, status)
}
@discardableResult
func run(_ executable: String, _ arguments: [String], at directory: URL? = nil,
         environment: [String: String]? = nil, capture: Bool = false) throws -> String {
    let process = Process()
    process.executableURL = URL(fileURLWithPath: executable)
    process.arguments = arguments
    process.currentDirectoryURL = directory
    process.environment = environment
    let output = capture ? Pipe() : nil
    if let output { process.standardOutput = output }
    try process.run()
    let data = output?.fileHandleForReading.readDataToEndOfFile()
    process.waitUntilExit()
    guard process.terminationReason == .exit && process.terminationStatus == 0 else {
        throw CommandFailure(status: process.terminationStatus == 0 ? 1 : process.terminationStatus)
    }
    return data.map { String(decoding: $0, as: UTF8.self) } ?? ""
}
func bootstrapMise(root: URL) throws -> URL {
    #if os(macOS)
    #if arch(arm64)
    let architecture = "arm64"
    let checksum = "bbfd47ef65c2278c4e9ba09b523beb1019365a3c0b9c9fc60f686dc16f358e0f"
    #elseif arch(x86_64)
    let architecture = "x64"
    let checksum = "167137820c857491cc649c5502276ad94e31edb4a5e9e6339aed8d812031d031"
    #else
    throw CloudError("Unsupported macOS architecture.")
    #endif
    // Official v2026.9.11 release asset digests; no mutable installer or Homebrew state.
    let directory = root.appendingPathComponent(".build-artifacts/cloud-tools")
    try FileManager.default.createDirectory(at: directory, withIntermediateDirectories: true)
    let binary = directory.appendingPathComponent("mise")
    try run("/usr/bin/curl", ["--fail", "--location", "--silent", "--show-error", "--retry", "3",
        "--proto", "=https", "--proto-redir", "=https", "--connect-timeout", "30", "--max-time", "300",
        "--output", binary.path,
        "https://github.com/jdx/mise/releases/download/v2026.9.11/mise-v2026.9.11-macos-\(architecture)"])
    let actual = try run("/usr/bin/shasum", ["-a", "256", binary.path], capture: true).split(separator: " ").first
    try requireCloud(actual == Substring(checksum), "mise checksum mismatch; refusing to execute downloaded binary.")
    try FileManager.default.setAttributes([.posixPermissions: 0o755], ofItemAtPath: binary.path)
    return binary
    #else
    throw CloudError("Xcode Cloud bootstrap requires macOS.")
    #endif
}
func cloudMain(_ arguments: [String], environment: [String: String]) throws {
    try requireCloud(arguments.count == 3, "Usage: XcodeCloud.swift <post-clone|post-xcodebuild> <ci_scripts path>")
    let scripts = URL(fileURLWithPath: arguments[2], isDirectory: true)
    if arguments[1] == "post-xcodebuild" {
        let (action, status) = try nativeAction(environment)
        // Preserve the original native failure even if artifacts or identity are unavailable.
        guard status == 0 else { throw CommandFailure(status: status) }
        guard action == "archive" else { return }
        let product = try JSONDecoder().decode(Product.self, from: Data(contentsOf: scripts.appendingPathComponent("Product.json")))
        let values = try identity(environment, product: product)
        guard let archive = environment["CI_ARCHIVE_PATH"], archive.hasPrefix("/"),
              FileManager.default.fileExists(atPath: archive) else {
            throw CloudError("Successful archive action requires an existing absolute CI_ARCHIVE_PATH.")
        }
        try run("/usr/bin/env", ["swift", scripts.appendingPathComponent("helpers/CheckArchive.swift").path,
            archive, "--expect-bundle-id", values.bundleID, "--expect-build-number", values.build,
            "--expect-version", product.marketingVersion])
        return
    }
    try requireCloud(arguments[1] == "post-clone", "Unknown Xcode Cloud phase.")
    guard let path = environment["CI_PRIMARY_REPOSITORY_PATH"], path.hasPrefix("/") else {
        throw CloudError("CI_PRIMARY_REPOSITORY_PATH must be an absolute checkout path.")
    }
    let root = URL(fileURLWithPath: path, isDirectory: true)
    let product = try JSONDecoder().decode(Product.self, from: Data(contentsOf: root.appendingPathComponent("Config/Product.json")))
    let values = try identity(environment, product: product)
    try values.configuration.write(to: root.appendingPathComponent("Config/Cloud.xcconfig"), atomically: true, encoding: .utf8)
    let mise = try bootstrapMise(root: root)
    var child = environment
    child["MISE_YES"] = "1"
    child["MISE_TRUSTED_CONFIG_PATHS"] = root.path
    child["PATH"] = mise.deletingLastPathComponent().path + ":" + (environment["PATH"] ?? "/usr/bin:/bin")
    try run(mise.path, ["install", "--locked"], at: root, environment: child)
    try run(mise.path, ["run", "--jobs", "1", "test:core", "project:check"], at: root, environment: child)
}
#if !CLOUD_HOOK_TESTS
do { try cloudMain(CommandLine.arguments, environment: ProcessInfo.processInfo.environment) }
catch let failure as CommandFailure { exit(failure.status) }
catch { FileHandle.standardError.write(Data("Xcode Cloud adapter failed: \(error)\n".utf8)); exit(1) }
#endif
